version: "3"

services:

# BD

  mysql_db:
    container_name: mysql_container
    image: mysql:5.7
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: some_password_of_ur_choice
      MYSQL_DATABASE: wordpress_database
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_user_password
    volumes:
      - mysql_vol:/var/lib/mysql
    restart: always
    
# Magento

  magento:
     depends_on:
       - mysql_db
     image: alexcheng/magento2:latest
     ports:
       - "8002:80"
     restart: always
     environment:
       MAGENTO_DB_HOST: db:3306
       MAGENTO_DB_USER: magento002
       MAGENTO_DB_PASSWORD: magento002
       MAGENTO_DB_NAME: magento002

# wordpress 

  wordpress:
    depends_on:
      - mysql_db
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql_db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_user_password
      WORDPRESS_DB_NAME: wordpress_database
    volumes:
      ["./:/var/www/html"]

# tomcat 

  db:
    image: de1m0s/postgres-compose:1.1
    container_name: tomcat-db-container
    environment:
      POSTGRES_PASSWORD: tomcat_password
      POSTGRES_USER: tomcat_user
      POSTGRES_DB: tomcat_db

    image: de1m0s/tomcat-compose:1.3
    environment:
      TOMCAT_DB_NAME: tomcat_db
      TOMCAT_DB_USER: tomcat_user
      TOMCAT_DB_PASSWORD: tomcat_password
      TOMCAT_DB_HOST: db
      TOMCAT_USER: tomcat-admin
      TOMCAT_PASSWORD: 12345678
      TOMCAT_DB_JNDI_NAME: jdbc/mainDB
      TOMCAT_EXTERNAL_FOLDER: /var/external-files/
      TOMCAT_DUMPS_FOLDER: /var/external-files/dumps
    ports:
      - "8001:8080"

volumes:
  mysql_vol: {}
  magento_data:
    driver: local
